# Setup
title:               'Hongbuly'
tagline:             'Hongbuly blog'
description:         'This is Hongbuly's blog.'
url:                 https://hongbuly.github.io
# baseurl:             ''
paginate:            5
permalink:           pretty
comments:            true

# About/contact
author:
  name:              Honghyun Youn
  url:               https://hongbuly.github.io
  email:             hongbulys@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
comment:
  provider: "disqus"
  disqus:
    shortname: "hongbuly"
